START_MESSAGE = """
Привет, {first_name}!
Я бот, который поможет тебе найти все неправильные глаголы
английского языка с их переводами!

Просто жми на кнопку ниже и следуй инструкции:
"""

SEND_WORD = """
Напишите неправильный глагол:
"""

irregular_verbs = {
    "be": ("was/were", "been", "быть"),
    "begin": ("began", "begun", "начинать"),
    "bend": ("bent", "bent", "сгибать, гнуть"),
    "bet": ("bet", "betted", "держать пари"),
    "bind": ("bound", "bound", "связать"),
    "bite": ("bit", "bitten", "кусать"),
    "bleed": ("bled", "bled", "кровоточить"),
    "blow": ("blew", "blown", "дуть"),
    "break": ("broke", "broken", "ломать"),
    "breed": ("bred", "bred", "выращивать"),
    "bring": ("brought", "brought", "приносить"),
    "broadcast": ("broadcast", "broadcasted", "распространять, разбрасывать"),
    "browbeat": ("browbeat", "browbeaten", "запугивать"),
    "build": ("built", "built", "строить"),
    "burn": ("burned", "burnt", "гореть, жечь"),
    "burst": ("burst", "burst", "взрываться, прорываться"),
    "bust": ("busted", "bust", "разжаловать"),
    "buy": ("bought", "bought", "покупать"),
    "can": ("could", "could", "мочь, уметь"),
    "cast": ("cast", "cast", "бросить, кинуть, вышвырнуть"),
    "catch": ("caught", "caught", "ловить, хватать, успеть"),
    "choose": ("chose", "chosen", "выбирать"),
    "cling": ("clung", "clung", "цепляться, льнуть"),
    "clothe": ("clothed", "clad", "одевать (кого-либо)"),
    "come": ("came", "come", "приходить"),
    "cost": ("cost", "cost", "стоить, обходиться (в какую-либо сумму)"),
    "creep": ("crept", "crept", "ползать"),
    "cut": ("cut", "cut", "резать, разрезать"),
    "deal": ("dealt", "dealt", "иметь дело"),
    "dig": ("dug", "dug", "копать"),
    "dive": ("dove", "dived", "нырять, погружаться"),
    "do": ("did", "done", "делать, выполнять"),
    "draw": ("drew", "drawn", "рисовать, чертить"),
    "dream": ("dreamed", "dreamt", "грезить, мечтать"),
    "drink": ("drank", "drunk", "пить"),
    "drive": ("drove", "driven", "управлять автомобилем"),
    "dwell": ("dwelt", "dwelled", "обитать, находиться"),
    "eat": ("ate", "eaten", "есть, кушать"),
    "fall": ("fell", "fallen", "падать"),
    "feed": ("fed", "fed", "кормить"),
    "feel": ("felt", "felt", "чувствовать"),
    "fight": ("fought", "fought", "драться, сражаться, бороться"),
    "find": ("found", "found", "находить"),
    "fit": ("fit", "fit", "подходить по размеру"),
    "flee": ("fled", "fled", "убегать, спасаться"),
    "fling": ("flung", "flung", "бросаться, ринуться"),
    "fly": ("flew", "flown", "летать"),
    "forbid": ("forbade", "forbidden", "запрещать"),
    "forecast": ("forecast", "forecast", "предсказывать, предвосхищать"),
    "foresee": ("foresaw", "foreseen", "предвидеть"),
    "foretell": ("foretold", "foretold", "предсказывать, прогнозировать"),
    "forget": ("forgot", "forgotten", "забывать"),
    "forgive": ("forgave", "forgiven", "прощать"),
    "forsake": ("forsook", "forsaken", "покидать"),
    "freeze": ("froze", "frozen", "замерзать"),
    "get": ("got", "gotten", "получать, достигать"),
    "give": ("gave", "given", "давать"),
    "go": ("went", "gone", "идти, ехать"),
    "grind": ("ground", "ground", "молоть, толочь"),
    "grow": ("grew", "grown", "расти"),
    "hang": ("hung", "hanged", "вешать, развешивать"),
    "have": ("had", "had", "иметь"),
    "hear": ("heard", "heard", "слышать"),
    "hew": ("hewed", "hewn", "рубить"),
    "hide": ("hid", "hidden", "прятаться, скрываться"),
    "hit": ("hit", "hit", "ударять, поражать"),
    "hold": ("held", "held", "держать, удерживать, фиксировать"),
    "hurt": ("hurt", "hurt", "ранить, причинить боль"),
    "inlay": ("inlaid", "inlaid", "вкладывать, вставлять, выстилать"),
    "input": ("input", "inputted", "входить"),
    "interweave": ("interwove", "interwoven", "воткать"),
    "keep": ("kept", "kept", "держать, хранить"),
    "kneel": ("knelt", "kneeled", "стать на колени"),
    "knit": ("knitted", "knit", "вязать"),
    "know": ("knew", "known", "знать, иметь представление (о чем-либо)"),
    "lay": ("laid", "laid", "класть, положить"),
    "lead": ("led", "led", "вести, руководить, управлять"),
    "lean": ("leaned", "leant", "опираться, прислоняться"),
    "leap": ("leaped", "leapt", "прыгать, скакать"),
    "learn": ("learnt", "learned", "учить"),
    "leave": ("left", "left", "покидать, оставлять"),
    "lend": ("lent", "lent", "одалживать, давать взаймы"),
    "let": ("let", "let", "позволять, предполагать"),
    "lie": ("lay", "lain", "лежать"),
    "light": ("lit", "lighted", "освещать"),
    "lose": ("lost", "lost", "терять"),
    "make": ("made", "made", "делать, производить, создавать"),
    "may": ("might", "might", "мочь, иметь возможность"),
    "mean": ("meant", "meant", "значить, иметь в виду"),
    "meet": ("met", "met", "встречать"),
    "miscast": ("miscast", "miscast", "неправильно распределять роли"),
    "misdeal": ("misdealt", "misdealt", "поступать неправильно"),
    "misdo": ("misdid", "misdone", "делать что-либо неправильно или небрежно"),
    "misgive": ("misgave", "misgiven", "внушать недоверия, опасения"),
    "mishear": ("misheard", "misheard", "ослышаться"),
    "mishit": ("mishit", "mishit", "промахнуться"),
    "mislay": ("mislaid", "mislaid", "класть не на место"),
    "mislead": ("misled", "misled", "ввести в заблуждение"),
    "misread": ("misread", "misread", "неправильно истолковывать"),
    "misspell": ("misspelled", "misspelled", "писать с ошибками"),
    "misspend": ("misspent", "misspent", "неразумно, зря тратить"),
    "mistake": ("mistook", "mistaken", "ошибаться"),
    "misunderstand": ("misunderstood", "misunderstood", "неправильно понимать"),
    "mow": ("mowed", "mown", "косить"),
    "offset": ("offset", "offset", "возмещать, вознаграждать, компенсировать"),
    "outbid": ("outbid", "outbid", "перебивать цену"),
    "outdo": ("outdid", "outdone", "превосходить"),
    "outfight": ("outfought", "outfought", "побеждать в бою"),
    "outgrow": ("outgrew", "outgrown", "вырастать из"),
    "output": ("output", "outputted"),
    "undertake": ("undertook", "undertaken", "предпринять"),
    "underwrite": ("underwrote", "underwritten", "подписываться"),
    "undo": ("undid", "undone", "уничтожать сделанное"),
    "unfreeze": ("unfroze", "unfrozen", "размораживать"),
    "unsay": ("unsaid", "unsaid", "брать назад свои слова"),
    "unwind": ("unwound", "unwound", "развертывать"),
    "uphold": ("upheld", "upheld", "поддерживать"),
    "upset": ("upset", "upset", "опрокинуться"),
    "wake": ("woke", "woken", "просыпаться"),
    "waylay": ("waylaid", "waylaid", "подстерегать"),
    "wear": ("wore", "worn", "носить (одежду)"),
    "weave": ("weave", "woven", "ткать"),
    "wed": ("wed", "wedded", "жениться, выдавать замуж"),
    "weep": ("wept", "wept", "плакать, рыдать"),
    "wet": ("wet", "wetted", "мочить, увлажнять"),
    "win": ("won", "won", "победить, выиграть"),
    "wind": ("wound", "wound", "заводить (механизм)"),
    "withdraw": ("withdrew", "withdrawn", "взять назад, отозвать"),
    "withhold": ("withheld", "withheld", "воздерживаться, отказывать"),
    "withstand": ("withstood", "withstood", "противостоять"),
    "wring": ("wrung", "wrung", "скрутить, сжимать"),
    "write": ("wrote", "written", "писать")
}
